# Managed by secret manager
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: secret-store--default--dummy-secret
  namespace: default
  labels:
    app: secret-manager.comame.dev
    secret-manager.comame.dev/name: dummy-secret
    secret-manager.comame.dev/type: plain
    secret-manager.comame.dev/id: dummy-secret
data:
  value: c2VjcmV0IQ==

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dummy-secret
spec:
  secretStoreRef:
    name: secret-store
    kind: SecretStore
  target:
    name: dummy-secret-actual
  data:
    - secretKey: key
      remoteRef:
        key: dummy-secret
