apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secret-store
  namespace: default
spec:
  provider:
    webhook:
      url: https://secret-manager.comame.dev/v1/secrets/default/{{ .remoteRef.key }}
      headers:
        Authorization: Bearer {{ .auth.token }}
      result:
        jsonPath: $.value
      secrets:
        - name: auth
          secretRef:
            name: secret-store

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: secret-store
  namespace: default

---
apiVersion: v1
kind: Secret
metadata:
  name: secret-store
  namespace: default
  annotations:
    kubernetes.io/service-account.name: secret-store
type: kubernetes.io/service-account-token

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-store
  namespace: default
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - list

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-store
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: secret-store
subjects:
  - kind: ServiceAccount
    name: secret-store
    namespace: default
